import 'package:flutter/material.dart';

import '../models/userdetails.dart';
class Dashboard extends StatelessWidget {
  final   List<Autogenerated> userdata;
  const Dashboard({Key? key,required this.userdata}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return SafeArea(child: Scaffold(
      appBar: AppBar(),
      body: Container(
        height: MediaQuery.of(context).size.height-50,
        child: Column(
          children: [
            Textuserdetails(headding: "User Firstname",value: userdata[0].userFirstname),
            Textuserdetails(headding: "User Email",value: userdata[0].userEmail),
            Textuserdetails(headding: "User Mobilenumber",value: userdata[0].userPhone),
          ],
        ),
      ),

    ));
  }
  Widget Textuserdetails({headding,value}){
    return Row(
      mainAxisAlignment: MainAxisAlignment.spaceBetween,
      children: [
        Text("$headding    :",style: TextStyle(fontSize: 15,color: Colors.grey),),
        Text(value,style: TextStyle(fontSize: 20,color: Colors.black,fontWeight: FontWeight.bold),),
      ],
    );
  }
}
