import 'package:flutter/material.dart';
import 'package:fluttertoast/fluttertoast.dart';
import 'package:syofttask/UI/dashboard.dart';

import '../models/userdetails.dart';
import '../services/loginservice.dart';
import '../styles.dart';
class LoginPage extends StatefulWidget {
  const LoginPage({Key? key}) : super(key: key);

  @override
  State<LoginPage> createState() => _LoginPageState();
}

class _LoginPageState extends State<LoginPage> {
  List<Autogenerated> userdata=[];
  TextEditingController useremail=TextEditingController();
  TextEditingController password=TextEditingController();
  @override
  Widget build(BuildContext context) {
    return SingleChildScrollView(
      child: Container(
        color: Colors.white,
        height: MediaQuery.of(context).size.height-150,
        child: Stack(
          children: [
            Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                SizedBox(height: 100,),
                Text("    Welcome Back ,",style: TextStyle(fontSize: 40),),
                Text("    Manoj",style: TextStyle(fontSize: 40,fontWeight: FontWeight.bold),),
                Padding(
                  padding: const EdgeInsets.only(left: 15,right: 15),
                  child: TextFormField(
                    controller: useremail,
                    decoration: InputDecoration(
                      filled: true,
                      hintText: "Email Address",
                      fillColor: Colors.white,
                      enabledBorder: UnderlineInputBorder(
                        borderSide: BorderSide(
                            style: BorderStyle.solid, color: Colors.grey),
                      ),
                      focusedBorder:  UnderlineInputBorder(
                        borderSide: BorderSide(
                            style: BorderStyle.solid, color: Colors.grey),
                      ),
                    ),
                    // set the focused border property here


                  ),
                ),
                Padding(
                  padding: const EdgeInsets.only(top: 25,left: 15,right: 15),
                  child: TextFormField(
                    controller: password,
                    decoration: InputDecoration(
                      filled: true,
                      hintText: "Password",
                      fillColor: Colors.white,
                      enabledBorder: UnderlineInputBorder(
                        borderSide: BorderSide(
                            style: BorderStyle.solid, color: Colors.grey),
                      ),
                      focusedBorder:  UnderlineInputBorder(
                        borderSide: BorderSide(
                            style: BorderStyle.solid, color: Colors.grey),
                      ),
                    ),
                    // set the focused border property here


                  ),
                ),
                SizedBox(height: 20,),
                Row(
                  children: [
                    SizedBox(width: 10,),
                    Image(
                        height: 30,
                        image:
                        AssetImage("${assetImagePath}facebook.png"
                        )
                    ),
                    SizedBox(width: 20,),
                    Image(
                        height: 40,
                        image:
                        AssetImage("${assetImagePath}google.png"
                        )
                    )


                  ],
                ),
                Spacer(),
                Row(
                  // mainAxisAlignment: MainAxisAlignment.spaceBetween,
                  children: [
                    SizedBox(width: 10,),
                    Text("Forgot password?",style: TextStyle(fontWeight: FontWeight.bold),),
                    Spacer(),
                    InkWell(
                      onTap: (){
                        loginPasswordValidate();
                      },
                      child: Container(
                        height: 40,
                        width: 50,
                        color: Colors.yellow,
                        child: Icon(Icons.arrow_right_alt,color: Colors.white,),
                      ),
                    ),
                    SizedBox(width: 10,),
                  ],
                )
              ],
            ),
            Positioned(
                bottom: 5,
                child: Container(
                  height: 10,
              color: Colors.red,
            ))
          ],
        )
      ),
    );
  }
  Future<void> loginPasswordValidate() async {
    if (useremail.text.trim() == "" ||
        password.text.trim() == "") {
      Fluttertoast.showToast(
          msg: "Please enter your user name and password.");
    } else {
      var response = await LoginService().validateUser(
        userName: useremail.text.trim(),
        password: password.text.trim()
      );
        if(response.isNotEmpty){
          setState((){
            userdata=response;
          });
          Navigator.of(context).pushReplacement(MaterialPageRoute(
              builder: (context) =>  Dashboard(userdata: userdata,)));
        }
    }
  }
}
