import 'package:flutter/material.dart';

import '../models/userdetails.dart';
import '../network/apihelper.dart';
import '../styles.dart';
import 'package:fluttertoast/fluttertoast.dart';

class LoginService {

  List<Autogenerated> userdata=[];
  Future<List<Autogenerated>> validateUser({

    required String userName, required String password}) async {
    try {
      if (userName.isEmpty || password.isEmpty) return [];

      String postUrl = '$url/userlogin';
      Map<String, dynamic> requestBody = {
          "user_email":userName,
          "user_password":password
      };

      Map<String, dynamic> response = await ApiHelper().post(path: postUrl, postData: requestBody);
 // print('response $response');
      if (response['status']) {
        for(int i=0;i<response['user_data'].length;i++){
          userdata.add(Autogenerated.fromJson(response['user_data'][i]));
        }
        // Map<String, dynamic> data = response['user_data'][0];
       // print(data);
        return userdata;
      } else {
        Fluttertoast.showToast(
            msg: response['msg'],
            toastLength: Toast.LENGTH_LONG,
            gravity: ToastGravity.BOTTOM,
            timeInSecForIosWeb: 1,
            backgroundColor: Colors.red,
            textColor: Colors.white,
            fontSize: bodyFont);
      }

    } catch (e) {
      await Fluttertoast.showToast(
        msg:
          'Cannot get requested data, please try later.'
              ); // : ${e.toString()}');
    }
    return [];
  }

  Future<Map<String, dynamic>> SingUp({
      required String userName, required String password,email,phonenumber}) async {
    try {
      if (userName.isEmpty || password.isEmpty) return {};

      String postUrl = '$url/user_registeration';
     var requestBody = {
          "user_firstname": userName,
          "user_lastname": "kanfgfgta",
          "user_email": email,
          "user_phone": phonenumber,
          "user_password": password,
          "user_city": "mani",
          "user_zipcode": "789989"
      };

      Map<String, dynamic> response =
      await ApiHelper().post(path: postUrl, postData: requestBody);
      print(response['status']);
      if (response['status']) {
        await Fluttertoast.showToast(
            msg: response['msg'],
            toastLength: Toast.LENGTH_LONG,
            gravity: ToastGravity.BOTTOM,
            timeInSecForIosWeb: 1,
            backgroundColor: Colors.green,
            textColor: Colors.white,
            fontSize: bodyFont);
        Map<String, dynamic> data = response;
        return data;
      } else {
        print(response['msg']);
       await Fluttertoast.showToast(
            msg: response['msg'],
            toastLength: Toast.LENGTH_LONG,
            gravity: ToastGravity.BOTTOM,
            timeInSecForIosWeb: 1,
            backgroundColor: Colors.red,
            textColor: Colors.white,
            fontSize: bodyFont);

      }
    } catch (e) {
      await Fluttertoast.showToast(
          msg:
          'Cannot get requested data, please try later.'
      ); // : ${e.toString()}');
    }
    return {};
  }

}